# -*- coding: utf-8 -*-
"""DA day-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duy0gEELFlqKmh0ICsmXxfQA-zCgOcOT
"""

import pandas as pd

# Create dataset
data = {'Marks': [35, 67, 89, 45, 72, 90, 55, 60]}
df = pd.DataFrame(data)

# Equal Width Binning (3 bins)
df['Equal_Width_Bins'] = pd.cut(df['Marks'], bins=3)

print(df)

import pandas as pd

data = {'Marks': [35, 67, 89, 45, 72, 90, 55, 60]}
df = pd.DataFrame(data)

# Equal Frequency Binning (3 bins)
df['Equal_Freq_Bins'] = pd.qcut(df['Marks'], q=3)

print(df)

bins = [0, 40, 60, 80, 100]
labels = ['Poor', 'Average', 'Good', 'Excellent']

df['Grade'] = pd.cut(df['Marks'], bins=bins, labels=labels)

print(df)

import pandas as pd
import matplotlib.pyplot as plt

# Dataset
marks = [35, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90]
df = pd.DataFrame({'Marks': marks})
plt.hist(df['Marks'], bins=5, edgecolor='black')
plt.title("Histogram of Marks")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.show()

bins = [30, 45, 60, 75, 90, 100]
labels = ['Very Low', 'Low', 'Medium', 'High', 'Very High']

df['Category'] = pd.cut(df['Marks'], bins=bins, labels=labels)

print(df)